// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ServicioApiCurso.Models;
//
//    var postModelReqService = PostModelReqService.FromJson(jsonString);

namespace ServicioApiCurso.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PostModelReqService
    {
        [JsonProperty("userId")]
        public int UserId { get; set; }

        [JsonProperty("id")]
        public int IdPost { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }

    public partial class PostModelReqService
    {
        public static List<PostModelReqService> FromJson(string json) => JsonConvert.DeserializeObject<List<PostModelReqService>>(json, ServicioApiCurso.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<PostModelReqService> self) => JsonConvert.SerializeObject(self, ServicioApiCurso.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
