// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ServicioApiCurso.Models;
//
//    var publishPostModelReqService = PublishPostModelReqService.FromJson(jsonString);

namespace ServicioApiCurso.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PublishPostModelReqService
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("userId")]
        public long UserId { get; set; }
    }

    public partial class PublishPostModelReqService
    {
        public static PublishPostModelReqService FromJson(string json) => JsonConvert.DeserializeObject<PublishPostModelReqService>(json, ServicioApiCurso.Models.PublishPostModelReqServiceConverter.Settings);
    }

    public static class PublishPostModelReqServiceSerialize
    {
        public static string ToJson(this PublishPostModelReqService self) => JsonConvert.SerializeObject(self, ServicioApiCurso.Models.PublishPostModelReqServiceConverter.Settings);
    }

    internal static class PublishPostModelReqServiceConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
